databases:
  - name: bibliosmart-db
    databaseName: bibliosmart
    user: bibliosmart_user
    plan: free

services:
  - type: web
    name: bibliosmart-app
    env: docker
    plan: free
    envVars:
      - key: APP_KEY
        value: "base64:tSNczExZGU++h+UYtpyF0GyxCshQMrf5NydW7czl63Q="
      - key: APP_NAME
        value: BiblioSmart
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: bibliosmart-db
          property: connectionString
      - key: MAIL_MAILER
        value: resend
      - key: RESEND_API_KEY
        value: re_iUQvMEE6_5Qfhkwf3jwnYAevvNYMP6ucN
      - key: MAIL_FROM_ADDRESS
        value: onboarding@resend.dev
      - key: MAIL_FROM_NAME
        value: BiblioSmart
